### ISSUE TITLE
target timeframes resetting and not calculating

### ISSUE THREAD

**Issue by corvus2606** [BottlecapDave/HomeAssistant-TargetTimeframes#27]
### Describe the bug

I've noticed over the last few days, that the target timeframes are clearing and not recalculating.  This has happened multiple times, including while the sensor is active. the sensor then sets to false, and any future times do not trigger it until I reload the extension.

I have 3 Target timeframes, and 2 rolling targets set up.  When this occurs, all of the timeframes clear.

I have attached debug logs from last night, the sensors reset at some point, but unfortunately i don't have a definite time. but it looks like around 11pm something happened

### Reproduction steps

cant reliably reproduce.  
Set up:
using your octopus agile integration, using the provided blueprint to set up the data source for target timeframes.
3 targets set up, some intermittent, some continuous:

![Image](https://github.com/user-attachments/assets/570aa5d6-1254-4716-9a37-022c9478ca20)

![Image](https://github.com/user-attachments/assets/3acc9c91-481a-43d8-8245-9f04d152e809)

![Image](https://github.com/user-attachments/assets/2757d4bd-96be-4781-8264-aab9a923f763)

2 rolling targets:

![Image](https://github.com/user-attachments/assets/a96f652e-5cfe-4ea0-aa23-4dcf8c95af74)

![Image](https://github.com/user-attachments/assets/830e78b6-8133-4095-b9a1-92a73a3c4ff8)

### Expected behaviour

calculated times should not reset.  If recalculated, new times should be found

### Integration Version

1.1.1

### Home Assistant Version

2025.5.3

### Fresh Install?

After upgrading

### Home Assistant Logs

Before 1am:

[home-assistant_target_timeframes_2025-06-06T10-24-48.853Z.log](https://github.com/user-attachments/files/20628415/home-assistant_target_timeframes_2025-06-06T10-24-48.853Z.log)

After 1am:

[home-assistant_target_timeframes_2025-06-06T10-28-45.696Z.log](https://github.com/user-attachments/files/20628419/home-assistant_target_timeframes_2025-06-06T10-28-45.696Z.log)

### Confirmation

- [x] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-TargetTimeframes)
- [x] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-TargetTimeframes/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry that youve encountered this issue. I personally haven't seen it. I'll try and look at your logs when I get a chance

**Comment by sshaikh** [comment]
I mistakenly raised a similar issue under the Octopus Energy integration here https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/1336. I've copied what I think are the relevant data points below (although to be clear it seems to be working now):

Here are the respective attributes. These were extracted at 2025-06-05T12:04:+01:00

Working:
```
name: 10_hours
hours: 1
hours_mode: exact_hours
type: Continuous
look_ahead_hours: 24
target_times_evaluation_mode: always
kind: rolling_target_rate
target_times: 
- start: '2025-06-05T14:30:00+01:00'
  end: '2025-06-05T15:00:00+01:00'
  value: 0.1092
  metadata:
    is_capped: false
- start: '2025-06-05T15:00:00+01:00'
  end: '2025-06-05T15:30:00+01:00'
  value: 0.103215
  metadata:
    is_capped: false

target_times_last_evaluated: 2025-06-04T23:29:45.607991+01:00
time_periods_incomplete: true
overall_average_value: 0.10621
overall_min_value: 0.103215
overall_max_value: 0.1092
current_duration_in_hours: 0
current_average_value: null
current_min_value: null
current_max_value: null
next_time: 2025-06-05T14:30:00+01:00
next_duration_in_hours: 1
next_average_value: 0.10620750000000001
next_min_value: 0.103215
next_max_value: 0.1092
icon: mdi:camera-timer
friendly_name: 10_hours (octopus_energy_import)
```

Not working:
```
name: rollling_test
hours: 1
hours_mode: exact_hours
type: Continuous
look_ahead_hours: 24
target_times_evaluation_mode: always
kind: rolling_target_rate
rolling_target: true
latest_values: false
time_periods_incomplete: true
overall_average_value: 0
overall_min_value: null
overall_max_value: null
current_duration_in_hours: 0
current_average_value: null
current_min_value: null
current_max_value: null
next_time: null
next_duration_in_hours: 0
next_average_value: null
next_min_value: null
next_max_value: null
icon: mdi:camera-timer
friendly_name: rollling_test (octopus_energy_import)
```

**Comment by corvus2606** [comment]
One thing I'm noticing is that evaluated times do not persist through a restart of HASS, this may be part of the problem, as I have an automation to restart HASS at 1AM if I have installed updates.

I've disabled that for testing. 

Should the calculated times be persisting through a restart? or at the very least, recalculated on start up?

I believe there is something else going on, but this may be part of it.

**Comment by sshaikh** [comment]
FWIW I first noticed the issue after a restart, and seem to have good results eventually after "long running".

Maybe the rates feed doesn't propagate between reboots? Might be worth adding a trigger to run it on ha startup too then.

**Comment by sshaikh** [comment]
Actually I just checked my 4 rolling targets and they're all unknown so there's definitely something fishy going on. They're set to always evaluate so expect something to be there.

**Comment by sshaikh** [comment]
It looks like mine become unavailable when either:

1. The configuration changes
2. The `next_time` is reached

I think both cases require an evaluation (the are all `rolling` sent to `always`), so it seems something is going awry there. 

Here is one that just hit its target time:

```
name: 10_hours
hours: 1
hours_mode: exact_hours
type: Continuous
look_ahead_hours: 24
target_times_evaluation_mode: always
kind: rolling_target_rate
target_times: 
- start: '2025-06-11T14:30:00+01:00'
  end: '2025-06-11T15:00:00+01:00'
  value: 0.11235
  metadata:
    is_capped: false
- start: '2025-06-11T15:00:00+01:00'
  end: '2025-06-11T15:30:00+01:00'
  value: 0.1092
  metadata:
    is_capped: false

target_times_last_evaluated: 2025-06-10T23:29:45.178812+01:00
time_periods_incomplete: true
overall_average_value: 0.11078
overall_min_value: 0.1092
overall_max_value: 0.11235
current_duration_in_hours: 1
current_average_value: 0.11077500000000001
current_min_value: 0.1092
current_max_value: 0.11235
next_time: null
next_duration_in_hours: 0
next_average_value: null
next_min_value: null
next_max_value: null
icon: mdi:camera-timer
friendly_name: 10_hours (octopus_energy_import)
```
